### ISSUE TITLE
Great project but I can't get SCCB to work!!

### ISSUE THREAD

**Issue by g8ecj** [take-iwiw/DigitalCamera_STM32#1]
Call stack goes:
ov7670_init
ov7670_write
HAL_I2C_Mem_Write
I2C_RequestMemoryWrite
I2C_WaitOnMasterAddressFlagUntilTimeout <-- fails with timeout

Logic analyser says there is a NACK instead of ACK (as expected) but how do I ignore this condition? Only the address part of the transaction is completed.

**Comment by iwatake2222** [comment]
Thank you for the report with detailed information. I actually had an similar issue with SCCB read operaion, but write operation was okay in my environment. So, there might be something depending on device.
 My workaround for read operation is to use HAL_I2C_Master_Transmit instead of HAL_I2C_Mem_Read and communicate with the sensor byte by byte, so that STM32 doesn't care ack/nack.
I think the same solution will work for write operation. I will give it a try next week. (I'm on vacation this week, sorry!)

BTW, do you supply MCLK to the sensor? (I use MCO in my project). Otherwise, the sensor doesn't work at all, then your analyser might consider it as NACK. (You said the address part was working, so I think it must be okay, though.)

**Comment by g8ecj** [comment]
Making progress - I had the PWRDN signal the wrong way up which caused the camera to be asleep all the time.
SCCB now works correctly, just trying to get sync to work (I'm not using all your code, just the parts I feel are necessary to prove the camera works OK).
More info - I had to reduce MCLK from 42MHz to 16MHz (derived from HSI) as frame rate was 51 fps which is outside spec for OV7670 (30fps max). I'm finding it difficult to get the registers set correctly - the documentation is very confusing!

**Comment by iwatake2222** [comment]
That's good. SCCB communication problem was just because of wrong PWRDN signal.
You can refer to br_lesson branch (https://github.com/take-iwiw/DigitalCamera_STM32/tree/br_lesson). This is a simple implementation of ov7670 driver and live view function.
When AGC enabled, fps may vary depending on brightness.
I recommend you take a look at OV7670 driver on Linux, and OV7670 Implementation Guide (not a datasheet). They are useful.

**Comment by ShikharJ** [comment]
@iwatake2222 I'm facing the same issue as described above. However, in my case, both the ` HAL_I2C_Mem_Write` and `HAL_I2C_Master_Transmit` are failing while reaching the `I2C_WaitOnMasterAddressFlagUntilTimeout` One thing to note here is that I'm not getting a timeout failure, rather a acknowledge failure in the below snippet:
```
while (__HAL_I2C_GET_FLAG(hi2c, Flag) == RESET)
  {
    if (__HAL_I2C_GET_FLAG(hi2c, I2C_FLAG_AF) == SET) <--- Fulfills this if condition
    {
      /* Generate Stop */
      SET_BIT(hi2c->Instance->CR1, I2C_CR1_STOP);

      /* Clear AF Flag */
      __HAL_I2C_CLEAR_FLAG(hi2c, I2C_FLAG_AF);

      hi2c->PreviousState       = I2C_STATE_NONE;
      hi2c->State               = HAL_I2C_STATE_READY;
      hi2c->Mode                = HAL_I2C_MODE_NONE;
      hi2c->ErrorCode           |= HAL_I2C_ERROR_AF;

      /* Process Unlocked */
      __HAL_UNLOCK(hi2c);

      return HAL_ERROR;  <----- Fails here
    }
....
}
```
